version: "3"
services:
  kademliaNodes:
    #image: kadlab:latest # Make sure your Docker image has this name.
    image: kademlia
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 25
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
#    environment:
#        Address: "127.0.0.1:3000"
#    ports:
#      - "4000:80"
    networks:
      - kademlia_network

networks:
  kademlia_network:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"
          gateway: "172.19.0.1"
